### Get all employees
GET http://localhost:8080/employees

### Add employee 1
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "department": "department",
  "salary": 1111
}

### Add employee 2
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "Petr",
  "lastName": "Petrov",
  "department": "department",
  "salary": 2222
}

### Add employee 3
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Sidorov",
  "department": "department",
  "salary": 3333
}